<?php
/**
 * Implements hook_block_info().
 */
function webcrt_block_info() {
	$blocks = array();

	$blocks['webcrt_block_room'] = array(
		'info' => t('WebCRT ClassRoom'),
		'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function webcrt_block_view($delta = '') {
	if (function_exists($delta . '_view')) {
		return call_user_func($delta . '_view');
	}
}

/**
 * Implements hook_block_configure().
 */
function webcrt_block_configure($delta = '') {
	if (function_exists($delta . '_configure')) {
		return call_user_func($delta . '_configure');
	}
}

/**
 * Implements hook_block_save().
 */
function webcrt_block_save($delta = '', $edit = array()) {
	if (function_exists($delta . '_save')) {
		return call_user_func($delta . '_save', $edit);
	}
}

/**
 * Block code to view webcrt_block_room
 */
function webcrt_block_room_view() {
	drupal_add_js(drupal_get_path('module', 'webcrt').'/SimpleWebRTC/simplewebrtc.bundle.js', 'file');
	drupal_add_js(drupal_get_path('module', 'webcrt').'/simplewebrtc.custom.js', 'file');
	drupal_add_css(drupal_get_path('module', 'webcrt').'/simplewebrtc.custom.css', 'file');
	$markup ='<button id="enableWebcrt">JoinIn This ClassRoom</button>
        <div class="videoContainer">
            <video id="localVideo" style="height: 150px;" oncontextmenu="return false;"></video>
            <div id="localVolume" class="volume_bar"></div>
        </div>
        <div id="remotes"></div><button id="switchvideo" play="on">on</button>';
	$block = array('subject' => 'JoinClassRoom', 'content' => $markup);

	

	return $block;
}

/**
 * Block code to configure webcrt_block_room
 */
function webcrt_block_room_configure() {
	$form = array();
	return $form;
}

/**
 * Block code to save webcrt_block_room
 */
function webcrt_block_room_save($edit = array()) {
}